import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { createInterface } from 'node:readline';
import { prepareCommand } from './spawn.js';

type RpcId = number | string;
type JsonObject = Record<string, unknown>;

export interface RpcNotification {
  method: string;
  params: unknown;
}

export interface RpcServerRequest extends RpcNotification {
  id: RpcId;
}

interface PendingRequest {
  resolve: (value: unknown) => void;
  reject: (error: Error) => void;
}

/** Small JSON-RPC 2.0 peer for Codex's headerless, newline-delimited wire format. */
export class JsonlRpcClient {
  private nextId = 0;
  private readonly pending = new Map<RpcId, PendingRequest>();
  private closed = false;

  constructor(
    private readonly sendLine: (line: string) => void,
    private readonly onNotification: (message: RpcNotification) => void = () => undefined,
    private readonly onServerRequest: (message: RpcServerRequest) => void = () => undefined,
  ) {}

  request<T = unknown>(method: string, params: unknown): Promise<T> {
    if (this.closed) return Promise.reject(new Error('Codex app-server connection is closed.'));
    const id = ++this.nextId;
    return new Promise<T>((resolve, reject) => {
      this.pending.set(id, { resolve: (value) => resolve(value as T), reject });
      this.write({ id, method, params });
    });
  }

  notify(method: string, params: unknown): void {
    if (this.closed) throw new Error('Codex app-server connection is closed.');
    this.write({ method, params });
  }

  respond(id: RpcId, result: unknown): void {
    if (this.closed) return;
    this.write({ id, result });
  }

  receive(line: string): void {
    let message: JsonObject;
    try {
      message = JSON.parse(line) as JsonObject;
    } catch {
      return;
    }

    const id = typeof message.id === 'number' || typeof message.id === 'string' ? message.id : undefined;
    const method = typeof message.method === 'string' ? message.method : undefined;

    if (id !== undefined && method) {
      this.onServerRequest({ id, method, params: message.params });
      return;
    }

    if (id !== undefined) {
      const pending = this.pending.get(id);
      if (!pending) return;
      this.pending.delete(id);
      if (message.error && typeof message.error === 'object') {
        const error = message.error as { message?: unknown; code?: unknown };
        pending.reject(
          new Error(
            `Codex app-server request failed${error.code === undefined ? '' : ` (${String(error.code)})`}: ${String(error.message ?? 'unknown error')}`,
          ),
        );
      } else {
        pending.resolve(message.result);
      }
      return;
    }

    if (method) this.onNotification({ method, params: message.params });
  }

  close(error = new Error('Codex app-server connection closed.')): void {
    if (this.closed) return;
    this.closed = true;
    for (const pending of this.pending.values()) pending.reject(error);
    this.pending.clear();
  }

  private write(message: JsonObject): void {
    this.sendLine(`${JSON.stringify(message)}\n`);
  }
}

/** Narrow compatibility facade over types generated by `codex app-server generate-ts`. */
export interface CodexModel {
  id: string;
  model?: string;
  displayName: string;
  hidden?: boolean;
  isDefault?: boolean;
  defaultReasoningEffort?: string;
  supportedReasoningEfforts?: { reasoningEffort: string; description?: string }[];
}

export interface CodexThread {
  id: string;
  name?: string | null;
  preview?: string;
  modelProvider?: string;
}

export interface CodexTurn {
  id: string;
  status?: string;
}

export type CodexApprovalDecision = 'accept' | 'acceptForSession' | 'decline' | 'cancel';
export type CodexSandbox = 'readOnly' | 'workspaceWrite' | 'dangerFullAccess';
export type CodexApprovalPolicy = 'untrusted' | 'on-request' | 'never';
export type CodexApprovalsReviewer = 'user' | 'auto_review';

export interface CodexAppServerOptions {
  command?: string;
  cwd: string;
  onNotification?: (message: RpcNotification) => void;
  onServerRequest?: (message: RpcServerRequest) => void;
  onExit?: (error: Error) => void;
}

export class CodexAppServer {
  private constructor(
    private readonly child: ChildProcessWithoutNullStreams,
    readonly rpc: JsonlRpcClient,
  ) {}

  static async start(options: CodexAppServerOptions): Promise<CodexAppServer> {
    const prepared = prepareCommand(options.command ?? 'codex', ['app-server']);
    const child = spawn(prepared.file, prepared.args, {
      cwd: options.cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsVerbatimArguments: prepared.windowsVerbatimArguments,
      windowsHide: true,
    });
    const rpc = new JsonlRpcClient(
      (line) => child.stdin.write(line),
      options.onNotification,
      options.onServerRequest,
    );
    const server = new CodexAppServer(child, rpc);
    const lines = createInterface({ input: child.stdout });
    lines.on('line', (line) => rpc.receive(line));

    let stderr = '';
    child.stderr.on('data', (chunk: Buffer | string) => {
      stderr = `${stderr}${String(chunk)}`.slice(-8000);
    });
    let finished = false;
    const finish = (error: Error) => {
      if (finished) return;
      finished = true;
      rpc.close(error);
      options.onExit?.(error);
    };
    child.once('error', finish);
    child.once('exit', (code, signal) => {
      const detail = stderr.trim();
      const error = new Error(
        `Codex app-server exited${code === null ? '' : ` with code ${code}`}${signal ? ` (${signal})` : ''}${detail ? `: ${detail}` : ''}`,
      );
      finish(error);
    });

    await rpc.request('initialize', {
      clientInfo: { name: 'agentmesh', title: 'AgentMesh', version: '0.1.0' },
      capabilities: {},
    });
    rpc.notify('initialized', {});
    return server;
  }

  async listModels(): Promise<CodexModel[]> {
    const models: CodexModel[] = [];
    let cursor: string | null | undefined;
    do {
      const result = await this.rpc.request<{ data: CodexModel[]; nextCursor?: string | null }>('model/list', {
        limit: 100,
        includeHidden: false,
        ...(cursor ? { cursor } : {}),
      });
      models.push(...result.data);
      cursor = result.nextCursor;
    } while (cursor);
    return models;
  }

  async startThread(input: {
    cwd: string;
    model?: string;
    approvalPolicy?: CodexApprovalPolicy;
    approvalsReviewer?: CodexApprovalsReviewer;
    sandbox?: CodexSandbox;
  }): Promise<CodexThread> {
    const result = await this.rpc.request<{ thread: CodexThread }>('thread/start', {
      cwd: input.cwd,
      serviceName: 'agentmesh',
      ...(input.model ? { model: input.model } : {}),
      ...(input.approvalPolicy ? { approvalPolicy: input.approvalPolicy } : {}),
      ...(input.approvalsReviewer ? { approvalsReviewer: input.approvalsReviewer } : {}),
      ...(input.sandbox ? { sandbox: sandboxMode(input.sandbox) } : {}),
    });
    return result.thread;
  }

  async resumeThread(threadId: string): Promise<CodexThread> {
    const result = await this.rpc.request<{ thread: CodexThread }>('thread/resume', { threadId });
    return result.thread;
  }

  async startTurn(input: {
    threadId: string;
    prompt: string;
    cwd: string;
    model?: string;
    effort?: string;
    summary?: 'auto' | 'concise' | 'detailed' | 'none';
    approvalPolicy?: CodexApprovalPolicy;
    approvalsReviewer?: CodexApprovalsReviewer;
    sandbox?: CodexSandbox;
  }): Promise<CodexTurn> {
    const result = await this.rpc.request<{ turn: CodexTurn }>('turn/start', {
      threadId: input.threadId,
      input: [{ type: 'text', text: input.prompt }],
      cwd: input.cwd,
      ...(input.model ? { model: input.model } : {}),
      ...(input.effort ? { effort: input.effort } : {}),
      ...(input.summary ? { summary: input.summary } : {}),
      ...(input.approvalPolicy ? { approvalPolicy: input.approvalPolicy } : {}),
      ...(input.approvalsReviewer ? { approvalsReviewer: input.approvalsReviewer } : {}),
      ...(input.sandbox ? { sandboxPolicy: sandboxPolicy(input.sandbox, input.cwd) } : {}),
    });
    return result.turn;
  }

  interruptTurn(threadId: string, turnId: string): Promise<unknown> {
    return this.rpc.request('turn/interrupt', { threadId, turnId });
  }

  archiveThread(threadId: string): Promise<unknown> {
    return this.rpc.request('thread/archive', { threadId });
  }

  respondToApproval(requestId: RpcId, decision: CodexApprovalDecision): void {
    this.rpc.respond(requestId, { decision });
  }

  respondToRequest(requestId: RpcId, result: unknown): void {
    this.rpc.respond(requestId, result);
  }

  close(): void {
    this.rpc.close();
    if (!this.child.killed) this.child.kill();
  }
}

function sandboxPolicy(sandbox: CodexSandbox, cwd: string): JsonObject {
  if (sandbox === 'readOnly') return { type: 'readOnly', networkAccess: false };
  if (sandbox === 'dangerFullAccess') return { type: 'dangerFullAccess' };
  return {
    type: 'workspaceWrite',
    writableRoots: [cwd],
    networkAccess: false,
    excludeTmpdirEnvVar: false,
    excludeSlashTmp: false,
  };
}

function sandboxMode(sandbox: CodexSandbox): string {
  if (sandbox === 'readOnly') return 'read-only';
  if (sandbox === 'dangerFullAccess') return 'danger-full-access';
  return 'workspace-write';
}

export interface SanitizedCodexActivity {
  threadId: string;
  turnId?: string;
  itemId?: string;
  kind: 'reasoningSummary' | 'command' | 'mcpTool' | 'fileChange' | 'contextCompaction' | 'message' | 'status' | 'error';
  status?: string;
  summary?: string;
  tool?: string;
  command?: string;
  cwd?: string;
  output?: string;
  exitCode?: number;
  durationMs?: number;
  files?: string[];
  diff?: string;
}

/** Translate only explicitly approved fields; never forward raw app-server objects. */
export function sanitizeCodexNotification(method: string, input: unknown): SanitizedCodexActivity | null {
  const params = object(input);
  const threadId = string(params.threadId);
  if (!threadId) return null;
  const common = {
    threadId,
    ...(string(params.turnId) ? { turnId: string(params.turnId) } : {}),
    ...(string(params.itemId) ? { itemId: string(params.itemId) } : {}),
  };

  if (method === 'item/reasoning/summaryTextDelta') {
    return { ...common, kind: 'reasoningSummary', summary: truncate(string(params.delta), 4000) };
  }
  if (method === 'turn/diff/updated') {
    return { ...common, kind: 'fileChange', diff: truncate(string(params.diff), 16_000) };
  }
  if (method === 'error') {
    const error = object(params.error);
    return { ...common, kind: 'error', summary: truncate(string(error.message), 2000) };
  }
  if (method === 'turn/started' || method === 'turn/completed') {
    const turn = object(params.turn);
    return {
      ...common,
      ...(string(turn.id) ? { turnId: string(turn.id) } : {}),
      kind: 'status',
      status: string(turn.status) || (method === 'turn/started' ? 'inProgress' : 'completed'),
    };
  }
  if (method !== 'item/started' && method !== 'item/completed') return null;

  const item = object(params.item);
  const itemId = string(item.id) || string(params.itemId);
  const base = { ...common, ...(itemId ? { itemId } : {}) };
  const type = string(item.type);
  if (type === 'commandExecution') {
    const exitCode = number(item.exitCode);
    const durationMs = number(item.durationMs);
    return {
      ...base,
      kind: 'command',
      command: truncate(string(item.command), 4000),
      cwd: truncate(string(item.cwd), 1000),
      status: truncate(string(item.status), 40),
      ...(string(item.aggregatedOutput) ? { output: truncate(string(item.aggregatedOutput), 16_000) } : {}),
      ...(exitCode !== undefined ? { exitCode } : {}),
      ...(durationMs !== undefined ? { durationMs } : {}),
    };
  }
  if (type === 'mcpToolCall' || type === 'dynamicToolCall') {
    const server = string(item.server);
    const tool = string(item.tool);
    return {
      ...base,
      kind: 'mcpTool',
      tool: truncate(server ? `${server}/${tool}` : tool, 160),
      status: truncate(string(item.status), 40),
    };
  }
  if (type === 'fileChange') {
    const changes = Array.isArray(item.changes) ? item.changes : [];
    const files = changes.map((change) => string(object(change).path)).filter(Boolean).slice(0, 200);
    const diff = changes.map((change) => string(object(change).diff)).filter(Boolean).join('\n');
    return {
      ...base,
      kind: 'fileChange',
      files,
      ...(diff ? { diff: truncate(diff, 16_000) } : {}),
      status: truncate(string(item.status), 40),
    };
  }
  if (type === 'agentMessage') {
    return { ...base, kind: 'message', summary: truncate(string(item.text), 4000) };
  }
  if (type === 'reasoning') {
    const summary = Array.isArray(item.summary) ? item.summary.filter((part): part is string => typeof part === 'string').join('\n') : '';
    return { ...base, kind: 'reasoningSummary', summary: truncate(summary, 4000) };
  }
  if (type === 'contextCompaction') {
    return { ...base, kind: 'contextCompaction', status: 'completed' };
  }
  return null;
}

function object(value: unknown): JsonObject {
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as JsonObject) : {};
}

function string(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function number(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) ? value : undefined;
}

function truncate(value: string, limit: number): string | undefined {
  if (!value) return undefined;
  return value.length <= limit ? value : `${value.slice(0, limit - 1)}…`;
}
